//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROFR.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.10.48.166/SRDHAadhaarInfoServices/services/Services.ServicesSOAP11port_" +
            "http/")]
        public string ROFR_WebReference_Services {
            get {
                return ((string)(this["ROFR_WebReference_Services"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bioauth3.ap.gov.in/SRDHAadhaarInfoServices/services/Services.ServicesSOAP1" +
            "1port_http/")]
        public string ROFR_WS_Aadhaar_Services {
            get {
                return ((string)(this["ROFR_WS_Aadhaar_Services"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bioauth3.ap.gov.in/DemoAuthenticationservice_140/services/Services.Service" +
            "sSOAP11port_http/")]
        public string ROFR_AdharNameService_Services {
            get {
                return ((string)(this["ROFR_AdharNameService_Services"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mcc.mgnregs.ap.gov.in/aphousingws/aphousingws.asmx")]
        public string ROFR_Nergaserviceprod_APHousingWS {
            get {
                return ((string)(this["ROFR_Nergaserviceprod_APHousingWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stage.mgnregs.ap.gov.in/aphousingws/aphousingws.asmx")]
        public string ROFR_Stagemgnergs_APHousingWS {
            get {
                return ((string)(this["ROFR_Stagemgnergs_APHousingWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mcc.mgnregs.ap.gov.in/aphousingws/aphousingws.asmx")]
        public string ROFR_getEGSJobCardInfoByUIDser_APHousingWS {
            get {
                return ((string)(this["ROFR_getEGSJobCardInfoByUIDser_APHousingWS"]));
            }
        }
    }
}
