//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ROFR.AdharNameService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicesSOAP11Binding", Namespace="http://bioauthentication/")]
    public partial class Services : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PIDBlockIrisAuthServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback PIDBlockFingerPrintAuthServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback DemoAuthenticationserviceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Services() {
            this.Url = global::ROFR.Properties.Settings.Default.ROFR_AdharNameService_Services;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PIDBlockIrisAuthServiceCompletedEventHandler PIDBlockIrisAuthServiceCompleted;
        
        /// <remarks/>
        public event PIDBlockFingerPrintAuthServiceCompletedEventHandler PIDBlockFingerPrintAuthServiceCompleted;
        
        /// <remarks/>
        public event DemoAuthenticationserviceCompletedEventHandler DemoAuthenticationserviceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:PIDBlockIrisAuthService", RequestNamespace="http://bioauthentication/xsd", ResponseNamespace="http://bioauthentication/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string PIDBlockIrisAuthService([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string uid_num, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string agency_name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string agency_code, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] encryptedPid, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] encSessionKey, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] encHmac, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string certificateIdentifier, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string dataType, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string udc, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rdsId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rdsVer, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string dpId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string dc, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mi, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mc) {
            object[] results = this.Invoke("PIDBlockIrisAuthService", new object[] {
                        uid_num,
                        agency_name,
                        agency_code,
                        encryptedPid,
                        encSessionKey,
                        encHmac,
                        certificateIdentifier,
                        dataType,
                        udc,
                        rdsId,
                        rdsVer,
                        dpId,
                        dc,
                        mi,
                        mc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PIDBlockIrisAuthServiceAsync(string uid_num, string agency_name, string agency_code, byte[] encryptedPid, byte[] encSessionKey, byte[] encHmac, string certificateIdentifier, string dataType, string udc, string rdsId, string rdsVer, string dpId, string dc, string mi, string mc) {
            this.PIDBlockIrisAuthServiceAsync(uid_num, agency_name, agency_code, encryptedPid, encSessionKey, encHmac, certificateIdentifier, dataType, udc, rdsId, rdsVer, dpId, dc, mi, mc, null);
        }
        
        /// <remarks/>
        public void PIDBlockIrisAuthServiceAsync(
                    string uid_num, 
                    string agency_name, 
                    string agency_code, 
                    byte[] encryptedPid, 
                    byte[] encSessionKey, 
                    byte[] encHmac, 
                    string certificateIdentifier, 
                    string dataType, 
                    string udc, 
                    string rdsId, 
                    string rdsVer, 
                    string dpId, 
                    string dc, 
                    string mi, 
                    string mc, 
                    object userState) {
            if ((this.PIDBlockIrisAuthServiceOperationCompleted == null)) {
                this.PIDBlockIrisAuthServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPIDBlockIrisAuthServiceOperationCompleted);
            }
            this.InvokeAsync("PIDBlockIrisAuthService", new object[] {
                        uid_num,
                        agency_name,
                        agency_code,
                        encryptedPid,
                        encSessionKey,
                        encHmac,
                        certificateIdentifier,
                        dataType,
                        udc,
                        rdsId,
                        rdsVer,
                        dpId,
                        dc,
                        mi,
                        mc}, this.PIDBlockIrisAuthServiceOperationCompleted, userState);
        }
        
        private void OnPIDBlockIrisAuthServiceOperationCompleted(object arg) {
            if ((this.PIDBlockIrisAuthServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PIDBlockIrisAuthServiceCompleted(this, new PIDBlockIrisAuthServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:PIDBlockFingerPrintAuthService", RequestNamespace="http://bioauthentication/xsd", ResponseNamespace="http://bioauthentication/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string PIDBlockFingerPrintAuthService([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string uid_num, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string agency_name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string agency_code, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] encryptedPid, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] encSessionKey, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] encHmac, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string certificateIdentifier, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string dataType, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string udc, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rdsId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rdsVer, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string dpId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string dc, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mi, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mc) {
            object[] results = this.Invoke("PIDBlockFingerPrintAuthService", new object[] {
                        uid_num,
                        agency_name,
                        agency_code,
                        encryptedPid,
                        encSessionKey,
                        encHmac,
                        certificateIdentifier,
                        dataType,
                        udc,
                        rdsId,
                        rdsVer,
                        dpId,
                        dc,
                        mi,
                        mc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PIDBlockFingerPrintAuthServiceAsync(string uid_num, string agency_name, string agency_code, byte[] encryptedPid, byte[] encSessionKey, byte[] encHmac, string certificateIdentifier, string dataType, string udc, string rdsId, string rdsVer, string dpId, string dc, string mi, string mc) {
            this.PIDBlockFingerPrintAuthServiceAsync(uid_num, agency_name, agency_code, encryptedPid, encSessionKey, encHmac, certificateIdentifier, dataType, udc, rdsId, rdsVer, dpId, dc, mi, mc, null);
        }
        
        /// <remarks/>
        public void PIDBlockFingerPrintAuthServiceAsync(
                    string uid_num, 
                    string agency_name, 
                    string agency_code, 
                    byte[] encryptedPid, 
                    byte[] encSessionKey, 
                    byte[] encHmac, 
                    string certificateIdentifier, 
                    string dataType, 
                    string udc, 
                    string rdsId, 
                    string rdsVer, 
                    string dpId, 
                    string dc, 
                    string mi, 
                    string mc, 
                    object userState) {
            if ((this.PIDBlockFingerPrintAuthServiceOperationCompleted == null)) {
                this.PIDBlockFingerPrintAuthServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPIDBlockFingerPrintAuthServiceOperationCompleted);
            }
            this.InvokeAsync("PIDBlockFingerPrintAuthService", new object[] {
                        uid_num,
                        agency_name,
                        agency_code,
                        encryptedPid,
                        encSessionKey,
                        encHmac,
                        certificateIdentifier,
                        dataType,
                        udc,
                        rdsId,
                        rdsVer,
                        dpId,
                        dc,
                        mi,
                        mc}, this.PIDBlockFingerPrintAuthServiceOperationCompleted, userState);
        }
        
        private void OnPIDBlockFingerPrintAuthServiceOperationCompleted(object arg) {
            if ((this.PIDBlockFingerPrintAuthServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PIDBlockFingerPrintAuthServiceCompleted(this, new PIDBlockFingerPrintAuthServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:DemoAuthenticationservice", RequestNamespace="http://bioauthentication/xsd", ResponseNamespace="http://bioauthentication/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string DemoAuthenticationservice([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string uid_num, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string beneficiary_name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string agency_name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string agency_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string gender) {
            object[] results = this.Invoke("DemoAuthenticationservice", new object[] {
                        uid_num,
                        beneficiary_name,
                        agency_name,
                        agency_code,
                        gender});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DemoAuthenticationserviceAsync(string uid_num, string beneficiary_name, string agency_name, string agency_code, string gender) {
            this.DemoAuthenticationserviceAsync(uid_num, beneficiary_name, agency_name, agency_code, gender, null);
        }
        
        /// <remarks/>
        public void DemoAuthenticationserviceAsync(string uid_num, string beneficiary_name, string agency_name, string agency_code, string gender, object userState) {
            if ((this.DemoAuthenticationserviceOperationCompleted == null)) {
                this.DemoAuthenticationserviceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDemoAuthenticationserviceOperationCompleted);
            }
            this.InvokeAsync("DemoAuthenticationservice", new object[] {
                        uid_num,
                        beneficiary_name,
                        agency_name,
                        agency_code,
                        gender}, this.DemoAuthenticationserviceOperationCompleted, userState);
        }
        
        private void OnDemoAuthenticationserviceOperationCompleted(object arg) {
            if ((this.DemoAuthenticationserviceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DemoAuthenticationserviceCompleted(this, new DemoAuthenticationserviceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void PIDBlockIrisAuthServiceCompletedEventHandler(object sender, PIDBlockIrisAuthServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PIDBlockIrisAuthServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PIDBlockIrisAuthServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void PIDBlockFingerPrintAuthServiceCompletedEventHandler(object sender, PIDBlockFingerPrintAuthServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PIDBlockFingerPrintAuthServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PIDBlockFingerPrintAuthServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DemoAuthenticationserviceCompletedEventHandler(object sender, DemoAuthenticationserviceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DemoAuthenticationserviceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DemoAuthenticationserviceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591